### ISSUE TITLE
Invalid value "datetime.date(2019, 7, 26)" found (row 0 column 1)

### ISSUE THREAD

**Issue by maffka123** [innobi/pantab#144]
**Describe the bug**

Getting error when saving pandas with dates inside:

```python
Traceback (most recent call last):
  File "C:\Users\M0555544\OneDrive - Magazine zum Globus AG\Desktop\Tableau_extract\main.py", line 74, in <module>
    te.run_full_load()
  File "C:\Users\M0555544\OneDrive - Magazine zum Globus AG\Desktop\Tableau_extract\main.py", line 27, in run_full_load
    self.el(0)
  File "C:\Users\M0555544\OneDrive - Magazine zum Globus AG\Desktop\Tableau_extract\main.py", line 51, in el
    self.extractor.write_hyper(d, file_path)
  File "C:\Users\M0555544\OneDrive - Magazine zum Globus AG\Desktop\Tableau_extract\extract.py", line 23, in write_hyper
    pantab.frames_to_hyper(dict_of_frames, path_to_database, hyper_process=hyper)
  File "C:\Users\M0555544\AppData\Local\pypoetry\Cache\virtualenvs\tableau-extract-21YZATXv-py3.9\lib\site-packages\pantab\_writer.py", line 211, in frames_to_hyper
    _insert_frame(
  File "C:\Users\M0555544\AppData\Local\pypoetry\Cache\virtualenvs\tableau-extract-21YZATXv-py3.9\lib\site-packages\pantab\_writer.py", line 154, in _insert_frame
    libpantab.write_to_hyper(df, null_mask, inserter._buffer, dtypes)
TypeError: Invalid value "datetime.date(2019, 7, 26)" found (row 0 column 1)
```

**To Reproduce**

```python
        with HyperProcess(telemetry=Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU) as hyper:
            pantab.frame_to_hyper(df=query_result_iter, database=path_to_database, table='Extract', hyper_process=hyper)
```

**Expected behavior**
the file would be stored without problems

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Additional context**

**Comment by WillAyd** [comment]
What are the dtypes  of your Dataframe? From the trace back I think the second column of your dataframe is stored as an object dtype rather than an actual datetime dtype, so you might need to explicitly call pd.to_datetime on that before writing

**Comment by maffka123** [comment]
Hi Thank you,

That was indeed the case, so I fixed it like that:

```python
        for col in df.columns:
            if df[col].dtype.name == 'object' and isinstance(df[col].values[0], datetime.date):
                df[col] = pd.to_datetime(df[col])
        with HyperProcess(telemetry=Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU) as hyper:
            pantab.frame_to_hyper(df=df, database=path_to_database, table='Extract', hyper_process=hyper)
```

It is a dataframe recieved from BQ storage API, so I assumed it would be correct..

**Comment by WillAyd** [comment]
Sounds good. FYI you don’t need to speak your own hyper process - the toll will do that automatically with the same defaults you have here
